# Check for mocha toml file - if missing run the following curl cmd
# curl -LO --output-dir ~/.config/alacritty/themes/ https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml
import = [
	"~/.config/alacritty/themes/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"
